export const WILDWESTFIGURES = [
  {
    id: 0,
    name: "Billy the Kid",
    lifespan: "",
    headline: "Billy the Kid, A Misunderstood Legend Of The West",
    personality: "",
    early: "",
    image1: "",
  },
  {
    id: 1,
    name: "Wyatt Earp",
    lifespan: "",
    headline: "Wyatt Earp, The West's Most Famous Lawman",
    personality: "",
    early: "",
    image1: "",
  },
  {
    id: 2,
    name: "Jessie James",
    lifespan: "",
    headline: "Jessie James and the James Gang, Ruthless Robbers Of The West",
    personality: "",
    early: "",
    image1: "",
  },
  {
    id: 3,
    name: "Wild Bill Hickok",
    lifespan: "",
    headline: "Wild Bill, a legendary gunslinger and sheriff",
    personality: "",
    early: "",
    image1: "",
  },
  {
    id: 4,
    name: "John Wesley Hardin",
    lifespan: "",
    headline: "John Wesley Hardin, The Meanest Gun In The West",
    personality: "",
    early: "",
    image1: "",
  },
];